name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3 # Update to the latest version that supports Node.js 20
    
          - name: Run blog post workflow
            uses: gautamkrishnar/blog-post-workflow@v4 # Update to the latest version that supports Node.js 20
            with:
              feed_url: "https://medium.com/feed/@priyaeswaran"
              github_token: ${{ secrets.GITHUB_TOKEN }}
                
